#!/bin/bash

if [ $# -lt 2 ]
then
    echo "Usage: $0 <exe> <input>"
    exit 1
else
    exeFile="$1"
    inputFile="$2"
    loggingArg="$3"

    if [ "$loggingArg" = "-log" ]
    then
        gdb -batch -nh -x trace.gdb -ex "r < $inputFile > tmp.txt" -ex "trace-asm" $exeFile
    else
        gdb -batch -nh -x trace.gdb -ex 'set logging file /dev/null' -ex 'set logging redirect on' -ex 'set logging on' -ex "r < $inputFile > tmp.txt" -ex "trace-asm" $exeFile
    fi
fi
